### ISSUE TITLE
Point/flat top

### ISSUE THREAD

**Issue by NeXTs** [rexxars/react-hexagon#1]
Hey

How to change angle of hexagon?
See https://codepen.io/wvr/pen/WrNgJp
Toggle **Point Top**, **Flat Top** buttons

I need both of these angles.
How to rotate hexagon to make it Flat Top?

**Comment by rexxars** [comment]
It would probably be best to draw it in the right shape from the start instead of rotating it, this way the fill would work in a predictable manner. I don't have time to address this in the near future, but I'll accept a pull request if anyone wants to provide the necessary changes.

**Comment by NeXTs** [comment]
And here are handy functions to handle that

http://www.thelow.co.uk/?p=128

In the comments function which able to proceed both angles

**Comment by rexxars** [comment]
ok, I couldn't stay away from this one ;)

Just released `1.1.0` with the `flatTop` prop (boolean). Centering content is a bit tricky, but sorta works.

**Comment by rexxars** [comment]
Demo at http://rexxars.github.io/react-hexagon/

**Comment by NeXTs** [comment]
Thank you! :smile:

**Comment by NeXTs** [comment]
@rexxars Seems to be that flatTop mode currently doesn't consider strokeWidth property if it's larger than 10

try this

```
<Hexagon
    flatTop
    style={{stroke: 'orange', strokeWidth: 25}} />
```

as result - hexagon will be cropped at the bottom

**Comment by rexxars** [comment]
Good catch. Pushed `1.1.1` with a fix, see if that works

**Comment by NeXTs** [comment]
Oh what a day! What a lovely day! :D

It works, thanks again!

**Comment by rexxars** [comment]
No problem, happy to help :)
